// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatigaEmt7an.Api.Data;

#nullable disable

namespace NatigaEmt7an.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502072102_AddIndexStatus")]
    partial class AddIndexStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NatigaEmt7an.Models.Models.Governorate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.OutCourses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EconomicsStatistics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NationalEdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReligionEdu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OutCourses");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SchoolAdministrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("SchoolAdministrationId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.SchoolAdministration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("SchoolAdministrations");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SchoolAdministrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalGrades")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("SchoolAdministrationId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SeatNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TotalGrades");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.StudentGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Ar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Biology")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Chemistry")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Foreign1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Foreign2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Geography")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Geology")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("History")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Math1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Math2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OutCoursesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Philosophy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Physics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Psychology")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OutCoursesId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentGrades");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.School", b =>
                {
                    b.HasOne("NatigaEmt7an.Models.Models.Governorate", "Governorate")
                        .WithMany("Schools")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatigaEmt7an.Models.Models.SchoolAdministration", "SchoolAdministration")
                        .WithMany("Schools")
                        .HasForeignKey("SchoolAdministrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");

                    b.Navigation("SchoolAdministration");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.SchoolAdministration", b =>
                {
                    b.HasOne("NatigaEmt7an.Models.Models.Governorate", "Governorate")
                        .WithMany("SchoolAdministrations")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.Student", b =>
                {
                    b.HasOne("NatigaEmt7an.Models.Models.Governorate", "Governorate")
                        .WithMany("Students")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatigaEmt7an.Models.Models.SchoolAdministration", "SchoolAdministration")
                        .WithMany("Students")
                        .HasForeignKey("SchoolAdministrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatigaEmt7an.Models.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");

                    b.Navigation("School");

                    b.Navigation("SchoolAdministration");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.StudentGrade", b =>
                {
                    b.HasOne("NatigaEmt7an.Models.Models.OutCourses", "OutCourses")
                        .WithMany()
                        .HasForeignKey("OutCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatigaEmt7an.Models.Models.Student", "Student")
                        .WithOne("StudentGrade")
                        .HasForeignKey("NatigaEmt7an.Models.Models.StudentGrade", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutCourses");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.Governorate", b =>
                {
                    b.Navigation("SchoolAdministrations");

                    b.Navigation("Schools");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.School", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.SchoolAdministration", b =>
                {
                    b.Navigation("Schools");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("NatigaEmt7an.Models.Models.Student", b =>
                {
                    b.Navigation("StudentGrade")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
